export const testIngredients = [
  {
    id: 0,
    name: "Mąka",
    app_id: null,
    type: "storage",
    amount: 15,
    unit: "szt.",
    expiry: 100,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Cukier",
    app_id: null,
    type: "storage",
    amount: 2,
    unit: "kg",
    expiry: 365,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Jajka",
    app_id: null,
    type: "storage",
    amount: 12,
    unit: "szt.",
    expiry: 28,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Masło",
    app_id: null,
    type: "storage",
    amount: 1,
    unit: "kg",
    expiry: 90,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Mleko",
    app_id: null,
    type: "storage",
    amount: 2,
    unit: "l",
    expiry: 7,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Kakao",
    app_id: null,
    type: "storage",
    amount: 0.5,
    unit: "kg",
    expiry: 365,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Kremówka",
    app_id: null,
    type: "storage",
    amount: 1,
    unit: "szt.",
    expiry: 5,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Ciastka",
    app_id: null,
    type: "storage",
    amount: 0.5,
    unit: "kg",
    expiry: 14,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Ser",
    app_id: null,
    type: "storage",
    amount: 1,
    unit: "kg",
    expiry: 30,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Mąka kukurydziana",
    app_id: null,
    type: "storage",
    amount: 0.5,
    unit: "kg",
    expiry: 365,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
  {
    id: 0,
    name: "Mąka orkiszowa",
    app_id: null,
    type: "storage",
    amount: 0.5,
    unit: "kg",
    expiry: 365,
    purchase_date: "2023-01-01",
    tag: 1,
    bookmark: false,
    recipes_id: null,
  },
];
